// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import Post__ReplyController from "./post/reply_controller"
application.register("post--reply", Post__ReplyController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import Ui__AccordionController from "./ui/accordion_controller"
application.register("ui--accordion", Ui__AccordionController)
